import { Link } from 'react-router-dom';
import { ArrowLeft } from 'lucide-react';
import {
 Breadcrumb,
 BreadcrumbList,
 BreadcrumbItem,
 BreadcrumbLink,
 BreadcrumbSeparator,
 BreadcrumbPage,
} from '@/components/ui/breadcrumb';

const TermsAndConditions =  => {
 return (
 <div className="min-h-screen bg-background text-foreground">
 {/* Header */}
 <div className="border-b border-silver/10">
 <div className="max-w-4xl mx-auto px-6 lg:px-8 py-6">
 <Breadcrumb>
 <BreadcrumbList>
 <BreadcrumbItem>
 <BreadcrumbLink asChild>
 <Link to="/" className="text-neon-cyan hover:text-neon-cyan/80">Home</Link>
 </BreadcrumbLink>
 </BreadcrumbItem>
 <BreadcrumbSeparator />
 <BreadcrumbItem>
 <BreadcrumbPage>Terms &amp; Conditions</BreadcrumbPage>
 </BreadcrumbItem>
 </BreadcrumbList>
 </Breadcrumb>
 </div>
 </div>

 <main className="max-w-4xl mx-auto px-6 lg:px-8 py-12 lg:py-20">
 {/* Back Link */}
 <Link
 to="/"
 className="inline-flex items-center gap-2 text-sm text-neon-cyan hover:text-neon-cyan/80 transition-colors mb-10"
 >
 <ArrowLeft className="w-4 h-4" />
 Back to Home
 </Link>

 <h1 className="font-display text-3xl lg:text-4xl font-bold text-foreground mb-2">
 Terms &amp; Conditions
 </h1>
 <p className="text-sm text-muted-foreground mb-12">
 Last updated: 27 February 2026
 </p>

 <div className="space-y-10 text-[15px] leading-[1.85] text-muted-foreground">
 {/* 1 */}
 <section>
 <h2 className="font-serif text-xl font-semibold text-foreground mb-3">1. Acceptance of Terms</h2>
 <p>
 By accessing or using the EconNexus platform ("Platform"), including its AI tutoring personas, revision notes, diagram banks, and any associated services, you agree to be bound by these Terms &amp; Conditions. If you do not agree, you must discontinue use immediately.
 </p>
 </section>

 {/* 2 */}
 <section>
 <h2 className="font-serif text-xl font-semibold text-foreground mb-3">2. Educational Disclaimer</h2>
 <p>
 All content generated by EconNexus AI personas — including but not limited to model answers, mark-scheme breakdowns, diagrams, and analytical commentary — is provided strictly as a <strong className="text-foreground">teaching and revision aid</strong>. It does not constitute:
 </p>
 <ul className="list-disc list-inside mt-3 space-y-1.5 pl-2">
 <li>Authoritative or guaranteed examination grades or marks.</li>
 <li>Professional legal, financial, or medical advice.</li>
 <li>Official content from any examination board (CIE, AQA, Edexcel, OCR, or others).</li>
 </ul>
 <p className="mt-3">
 Users should always consult official syllabuses, mark schemes, and examiner reports published by their respective examination board for definitive guidance. EconNexus makes no warranty, express or implied, regarding the accuracy or completeness of AI-generated content.
 </p>
 </section>

 {/* 3 */}
 <section>
 <h2 className="font-serif text-xl font-semibold text-foreground mb-3">3. Academic Integrity</h2>
 <p>
 Users of this Platform agree to uphold the highest standards of academic honesty. You must <strong className="text-foreground">not</strong>:
 </p>
 <ul className="list-disc list-inside mt-3 space-y-1.5 pl-2">
 <li>Submit AI-generated responses as your own original work in any assessed coursework, examination, or internal assessment.</li>
 <li>Use the Platform to facilitate or commit plagiarism, collusion, or any other form of academic malpractice as defined by your institution or examination board.</li>
 <li>Share AI-generated model answers in a manner that enables others to breach academic integrity policies.</li>
 </ul>
 <p className="mt-3">
 EconNexus reserves the right to suspend or terminate accounts found to be in violation of this clause.
 </p>
 </section>

 {/* 4 */}
 <section>
 <h2 className="font-serif text-xl font-semibold text-foreground mb-3">4. Fair Use &amp; System Protection</h2>
 <p>
 To ensure equitable access and protect the Platform's infrastructure, the following restrictions apply:
 </p>
 <ul className="list-disc list-inside mt-3 space-y-1.5 pl-2">
 <li>Automated scraping, bot-driven requests, or any high-frequency programmatic access to the Platform is strictly prohibited.</li>
 <li>Users must not attempt to reverse-engineer, decompile, or extract the underlying AI prompts, system instructions, or persona logic.</li>
 <li>Rate limits may be applied at the Platform's discretion. Excessive usage patterns that degrade service for other users may result in temporary or permanent access restrictions.</li>
 </ul>
 </section>

 {/* 5 */}
 <section>
 <h2 className="font-serif text-xl font-semibold text-foreground mb-3">5. Intellectual Property</h2>
 <p>
 <strong className="text-foreground">Platform IP:</strong> All AI personas (including but not limited to "Nexus", "Chemistry", "Psychology", and associated prompt logic), custom diagrams, design systems, branded content, and proprietary algorithms are the exclusive intellectual property of EconNexus and its founder.
 </p>
 <p className="mt-3">
 <strong className="text-foreground">User IP:</strong> Students and users retain full ownership of any original work they upload or input into the Platform (e.g., essay drafts, data sets, or personal notes). EconNexus does not claim ownership over user-submitted content.
 </p>
 <p className="mt-3">
 <strong className="text-foreground">Licence Grant:</strong> By submitting content to the Platform, you grant EconNexus a limited, non-exclusive, royalty-free licence to process and analyse your input solely for the purpose of generating AI responses during your session. This licence does not extend to storage, redistribution, or commercial use of your content.
 </p>
 </section>

 {/* 6 */}
 <section>
 <h2 className="font-serif text-xl font-semibold text-foreground mb-3">6. Data &amp; Privacy</h2>
 <p>
 EconNexus is committed to protecting user privacy. Chat sessions may be transiently processed to generate responses but are not permanently stored or used for model training unless explicitly stated. For full details, please refer to our <Link to="/privacy" className="text-neon-cyan hover:underline">Privacy Policy</Link>.
 </p>
 </section>

 {/* 7 */}
 <section>
 <h2 className="font-serif text-xl font-semibold text-foreground mb-3">7. Limitation of Liability</h2>
 <p>
 To the fullest extent permitted by applicable law, EconNexus, its founder, contributors, and affiliates shall not be liable for any direct, indirect, incidental, or consequential damages arising from the use of, or inability to use, the Platform or its AI-generated content — including but not limited to examination outcomes, academic decisions, or reliance on AI responses.
 </p>
 </section>

 {/* 8 */}
 <section>
 <h2 className="font-serif text-xl font-semibold text-foreground mb-3">8. Modifications to Terms</h2>
 <p>
 EconNexus reserves the right to update or modify these Terms at any time. Material changes will be communicated via the Platform. Continued use after such changes constitutes acceptance of the revised Terms.
 </p>
 </section>

 {/* 9 */}
 <section>
 <h2 className="font-serif text-xl font-semibold text-foreground mb-3">9. Governing Law</h2>
 <p>
 These Terms shall be governed by and construed in accordance with the laws of Pakistan. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the courts of Pakistan.
 </p>
 </section>

 {/* 10 */}
 <section>
 <h2 className="font-serif text-xl font-semibold text-foreground mb-3">10. Contact</h2>
 <p>
 For any questions regarding these Terms, please reach out to us through the Platform.
 </p>
 </section>
 </div>
 </main>
 </div>
 );
};

export default TermsAndConditions;
